# Default configuration for Simple OPDS

# Title for the root of the OPDS library
# Default: 'Simple OPDS'
title = 'Simple OPDS'

# Subdomain that OPDS will be served from
# Default: '/'
base_path = '/'

# Folder that contains content to be served
# Default: './content/'
content_path = './content/'

# Config for serving partial OPDS feeds, i.e. splitting the feed into multiple pages when it reaches a certain length 
[partial]
# Default: true
enabled = true
# Default: 50
page_size = 50

# Whether a full OPDS feed should be served to facilitate crawling and aggregation.
# Default: false
complete = false